[package]
name = "car-simulation"
version = "0.1.0"
edition = "2018"

[dependencies]
raqote = "0.7.8"
minifb = "0.19.3"
resvg = "0.19.0"
usvg = "0.19.0"
tiny-skia = "0.6.1"
lazy_static = "1.4.0"
font-kit = "0.5.0"